### ISSUE TITLE
rake task not working

### ISSUE THREAD

**Issue by ghost** [cloudhead/toto#50]
Hello:

I'm running into issue trying to use the 'rake new' task.  I am able to publish perfect fine by hand, but if i try to generate an article with rake, I run into the following issue:

{REMOVED}:myNewBlog {REMOVED}$ rake --trace new 
(in {REMOVED}/myNewBlog)
rake aborted!
no such file to load -- toto
/usr/local/lib/ruby/site_ruby/1.8/rubygems/custom_require.rb:31:in `gem_original_require'
/usr/local/lib/ruby/site_ruby/1.8/rubygems/custom_require.rb:31:in`require'
/Users/guy_montag_old/development/myNewBlog/Rakefile:1
/usr/local/lib/ruby/gems/1.8/gems/rake-0.8.7/lib/rake.rb:2383:in `load'
/usr/local/lib/ruby/gems/1.8/gems/rake-0.8.7/lib/rake.rb:2383:in`raw_load_rakefile'
/usr/local/lib/ruby/gems/1.8/gems/rake-0.8.7/lib/rake.rb:2017:in `load_rakefile'
/usr/local/lib/ruby/gems/1.8/gems/rake-0.8.7/lib/rake.rb:2068:in`standard_exception_handling'
/usr/local/lib/ruby/gems/1.8/gems/rake-0.8.7/lib/rake.rb:2016:in `load_rakefile'
/usr/local/lib/ruby/gems/1.8/gems/rake-0.8.7/lib/rake.rb:2000:in`run'
/usr/local/lib/ruby/gems/1.8/gems/rake-0.8.7/lib/rake.rb:2068:in `standard_exception_handling'
/usr/local/lib/ruby/gems/1.8/gems/rake-0.8.7/lib/rake.rb:1998:in`run'
/usr/local/lib/ruby/gems/1.8/gems/rake-0.8.7/bin/rake:31
/usr/local/bin/rake:19:in `load'
/usr/local/bin/rake:19

**Comment by ghost** [comment]
Resolved my issue.  Never installed toto and thin locally (sudo gem install toto thin).

Apologies for the ticket.
