### ISSUE TITLE
Rack::Lint::LintError - wrong Content-Length

### ISSUE THREAD

**Issue by ixti** [cloudhead/toto#91]
Not sure what cause this problem, but sometimes I have this error:

```
E, [2011-07-25T04:21:33.624016 #20714] ERROR -- : app error: Content-Length header was 17471, but should be 17477 (Rack::Lint::LintError)
E, [2011-07-25T04:21:33.624714 #20714] ERROR -- : /home/ixti/.rvm/gems/ruby-1.9.2-p180/gems/rack-1.3.1/lib/rack/lint.rb:19:in `assert'
E, [2011-07-25T04:21:33.624988 #20714] ERROR -- : /home/ixti/.rvm/gems/ruby-1.9.2-p180/gems/rack-1.3.1/lib/rack/lint.rb:501:in `verify_content_length'
E, [2011-07-25T04:21:33.625180 #20714] ERROR -- : /home/ixti/.rvm/gems/ruby-1.9.2-p180/gems/rack-1.3.1/lib/rack/lint.rb:525:in `each'
E, [2011-07-25T04:21:33.625456 #20714] ERROR -- : /home/ixti/.rvm/gems/ruby-1.9.2-p180/gems/rack-1.3.1/lib/rack/body_proxy.rb:26:in `method_missing'
E, [2011-07-25T04:21:33.625518 #20714] ERROR -- : /home/ixti/.rvm/gems/ruby-1.9.2-p180/gems/unicorn-4.0.1/lib/unicorn/http_response.rb:41:in `http_response_write'
E, [2011-07-25T04:21:33.625699 #20714] ERROR -- : /home/ixti/.rvm/gems/ruby-1.9.2-p180/gems/unicorn-4.0.1/lib/unicorn/http_server.rb:526:in `process_client'
E, [2011-07-25T04:21:33.625748 #20714] ERROR -- : /home/ixti/.rvm/gems/ruby-1.9.2-p180/gems/unicorn-4.0.1/lib/unicorn/http_server.rb:585:in `worker_loop'
E, [2011-07-25T04:21:33.626212 #20714] ERROR -- : /home/ixti/.rvm/gems/ruby-1.9.2-p180/gems/unicorn-4.0.1/lib/unicorn/http_server.rb:475:in `spawn_missing_workers'
E, [2011-07-25T04:21:33.626499 #20714] ERROR -- : /home/ixti/.rvm/gems/ruby-1.9.2-p180/gems/unicorn-4.0.1/lib/unicorn/http_server.rb:135:in `start'
E, [2011-07-25T04:21:33.626557 #20714] ERROR -- : /home/ixti/.rvm/gems/ruby-1.9.2-p180/gems/unicorn-4.0.1/bin/unicorn:121:in `<top (required)>'
E, [2011-07-25T04:21:33.626604 #20714] ERROR -- : /home/ixti/.rvm/gems/ruby-1.9.2-p180/bin/unicorn:19:in `load'
E, [2011-07-25T04:21:33.626650 #20714] ERROR -- : /home/ixti/.rvm/gems/ruby-1.9.2-p180/bin/unicorn:19:in `<main>'
```

Difference between expected length and actual is also different from time to time. Error appears on any page, but only sometimes, in other words it appears randomly and I can see it ONLY in log output when RACK_ENV=development.

My ruby version: 1.9.2-p180

**Comment by ixti** [comment]
Will got fixed with pull request #93
